### ISSUE TITLE
question on getting zero kl-divergence

### ISSUE THREAD

**Issue by Ivamcoder** [YannDubs/disentangling-vae#50]
Hi @YAnnDubs,

I have a problem in my own code, and I do not know how to solve that as I am new to VAEs models,
My kl divergence loss becomes so small close to zero, I did put some annealing function , but still the KL-loss becomes close too zero even when the annealing weight is zero,
In your opinion what should I do to train correctly :( ?

![image](https://user-images.githubusercontent.com/43126756/62418315-60b95e00-b6a9-11e9-9e91-7b35718fe116.png)

Thanks,

**Comment by YannDubs** [comment]
It is a bit hard to say without knowing what you do exactly. Here's what I would do to know where the issue comes from
1/ Make sure the KL is not 0 if you remove it from the loss. I.e. use a weight of 0 (no annealing, 0 from the start). 
2/ Compare the KL (in 1) with the reconstruction loss in the same setting. Maybe the reconstruction loss is neglectable compared to the KL.
3/ If the reconstruction loss is neglectable you are either using a very strange task or not computing it correctly. Specifically, make sure you are averaging over the correct values when computing the loss (i.e. the number of pixels, the batch, the channels ...).
